USE DATABASE CGM_HEALTH;
USE SCHEMA ANALYTICS;

SET DAMAGE_BASELINE = 140;
SET DAMAGE_POWER = 3;

CREATE OR REPLACE TABLE GLUCOSE_FEATURES AS
SELECT
    TIMESTAMP,
    GLUCOSE_VALUE,
    CASE
        WHEN GLUCOSE_VALUE > $DAMAGE_BASELINE 
        THEN POW(GLUCOSE_VALUE - $DAMAGE_BASELINE, $DAMAGE_POWER)
        ELSE 0
    END AS GLYCATION_INDEX
FROM
    CGM_HEALTH.ANALYTICS.RAW_READINGS
WHERE 
    GLUCOSE_VALUE IS NOT NULL;

-- SMOKE TEST --
SELECT * FROM GLUCOSE_FEATURES WHERE GLYCATION_INDEX > 0 LIMIT 10;